
export const GETPUSHMESSAGELIST_SUCCESS = 'GETPUSHMESSAGELIST_SUCCESS';//成功
export const GETPUSHMESSAGELIST_ERROR = 'GETPUSHMESSAGELIST_ERROR';//错误
export const GETPUSHMESSAGELIST_FAIL = 'GETPUSHMESSAGELIST_FAIL';//失败
export const GETPUSHMESSAGELIST_DOING = 'GETPUSHMESSAGELIST_DOING';//准备刷新
export const GETPUSHMESSAGELIST_LOADMORE = 'GETPUSHMESSAGELIST_LOADMORE';//加载更多
export const GETPUSHMESSAGELISTDATA = 'GETPUSHMESSAGELISTDATA';